version: '3.8'

services:
  app:
    image: deckard54/pms-backend-spring-boot:latest
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/deckard
      SPRING_DATASOURCE_USERNAME: postgresql
      SPRING_DATASOURCE_PASSWORD: barca
    networks:
      - deckard-network
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: deckard
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: barca
    networks:
      - deckard-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresql" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  deckard-network:
