spring:
  application:
    name: deckard-pms-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: barca
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083